/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.database_5318;

/**
 *
 * @author Em-kun
 */
public class MainMenu extends javax.swing.JFrame {

    /**
     * Creates new form MainMenu
     */
    public MainMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Customers_Page = new javax.swing.JButton();
        Publication_Page = new javax.swing.JButton();
        Subscription_Page = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Customers_Page.setText("Customers Info");
        Customers_Page.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Customers_PageActionPerformed(evt);
            }
        });

        Publication_Page.setText("Publication Info");
        Publication_Page.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Publication_PageActionPerformed(evt);
            }
        });

        Subscription_Page.setText("Subscription Info");
        Subscription_Page.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Subscription_PageActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(154, 154, 154)
                .addComponent(Customers_Page)
                .addGap(237, 237, 237)
                .addComponent(Publication_Page)
                .addGap(293, 293, 293)
                .addComponent(Subscription_Page)
                .addContainerGap(205, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(372, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Customers_Page)
                    .addComponent(Publication_Page)
                    .addComponent(Subscription_Page))
                .addGap(388, 388, 388))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Customers_PageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Customers_PageActionPerformed
        // TODO add your handling code here:
        Customer_Page customer_Page = new Customer_Page();
        customer_Page.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Customers_PageActionPerformed

    private void Publication_PageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Publication_PageActionPerformed
        // TODO add your handling code here:
        Publication_Page publication_Page = new Publication_Page();
        publication_Page.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Publication_PageActionPerformed

    private void Subscription_PageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Subscription_PageActionPerformed
        // TODO add your handling code here:
        Subscription_Page subscription_Page = new Subscription_Page();
        subscription_Page.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Subscription_PageActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Customers_Page;
    private javax.swing.JButton Publication_Page;
    private javax.swing.JButton Subscription_Page;
    // End of variables declaration//GEN-END:variables
}
